version: "3.7"

services:
  api:
    build: ./api/
    volumes:
      - ./api/data:/app/data
    ports:
      - 8080:8080
  frontend:
    build: ./frontend/
    ports:
      - 3000:3000
    depends_on:
      - api

