
app:
  settings:
    scheduleTimeInMinutes: 1
    pauseTimeBetweenActionsInSeconds: 15
    optimalResponseThreshold: 500
    maximalResponseThreshold: 3000
    tests_yaml_path: ./data/tests-yaml/
    api:
      expectedStatus: 200

spring:
  task:
    scheduling:
      pool:
        size: 1
  datasource:
    url: jdbc:h2:file:./data/h2/h2db;AUTO_SERVER=TRUE  #jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

